version: '2'

services:

  v2ray:
    image: v2ray/official
    container_name: v2ray-server
    restart: unless-stopped
    network_mode: host
    env_file:
      - ../../../v2ray.env
    volumes:
      - ./config.json.template:/etc/v2ray/config.json.template:ro
      - ./start.sh:/start.sh:ro
      - ./log:/var/log/v2ray
    command: ['/start.sh']
