version: '2'

services:

  nginx:
    image: fengzhou/nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro
      - ./logs:/var/logs/nginx
