#!/usr/bin/env ansible-playbook

---
- hosts: cloud
  gather_facts: true
  become: true
  pre_tasks:
    - name: Ensure packages installed
      yum:
        name: "{{ item }}"
      with_items:
        - python2-pip
        - docker-compose
    - name: Ensure pip packages installed
      pip:
        name: "{{ item }}"
      with_items:
        - docker
        - docker-compose
  tasks:
    - name: Ensure App Started
      docker_service:
        project_src: "{{ root_dir }}/aws-deploy/apps/{{ item }}"
        state: present
      with_items:
        - vpn
        - nginx
        - v2ray
    - name: Update VPN Domain
      import_role:
        name: dnspod-myip
      vars:
        dnspod_host: "{{ vpn_host }}"
        dnspod_domain: "{{ domain }}"
    - name: Get my public IP
      ipify_facts:
    - name: Notify via Slack
      slack:
        username: "cloud-bot"
        icon_emoji: ":cloud:"
        token: "{{ slack_token }}"
        msg: "{{ vpn_host }}.{{ domain }} is ready at IP {{ ipify_public_ip }}, please wait for a while to connect."
