name: deploy aws ec2
on: repository_dispatch
jobs:
  ec2:
    name: Deploy to AWS EC2
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: prepare .extra_vars
      env:
        EXTRA_VARS: ${{ secrets.EXTRA_VARS }}
      run: .github/workflows/ansible_vars.sh
    - name: install boto
      run: pip install boto
    - name: install boto3
      run: pip install boto3
    - name: run ansible
      run: ansible-playbook playbook.yml -e @.extra_vars
